[package]
name = "ultraloglog"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Ruihang Xia <waynestxia@gmail.com>"]
description = "Rust implementation of the UltraLogLog algorithm"
readme = "README.md"
repository = "https://github.com/waynexia/ultraloglog"
keywords = ["ultraloglog", "algorithm", "sketch", "probabilistic", "hyperloglog"]
categories = ["data-structures", "algorithms"]

[dependencies]

[dev-dependencies]
criterion = "0.5"
rand = "0.8"

[[bench]]
name = "ultraloglog"
harness = false
